### ISSUE TITLE
Utility not compatible with python3

### ISSUE THREAD

**Issue by sirajcmr** [DMTF/python-redfish-utility#1]
When we run the following command, we get an error

C:\Python34> python.exe C:\python-redfish-utility\src\rdmc.py
  File "C:\python-redfish-utility\src\rdmc.py", line 69
    except Exception, excp:
                    ^
SyntaxError: invalid syntax.

We are very new to python and restapi. As Gen9 and newer generation servers will be using restapi, we planned to try out.  Could you let us know what mistakes we are making.

**Comment by tomasg2012** [comment]
This exception statement is for Python 2.7, not Python 3 and up.  I'm guessing this tool was designed to be used with 2.7, which would require setting up and running Python 2.7 for this particular tool.

**Comment by sirajcmr** [comment]
Thanks. We are using 3.4 version of Python. Do we have any plan to get it working with newer version of Python?

Appreciate your assistance.

**Comment by jbobzin-insyde** [comment]
The current readme does not give information on supported python versions

**Comment by tomasg2012** [comment]
Ultimately we should be working towards turning all tools into python3 programs, this tool would need to be looked into to see if a conversion is an easy process.

**Comment by mraineri** [comment]
7/6 update: just noting that this is still in @LumbaJack's backlog to work on

**Comment by mraineri** [comment]
Might be worth doling out to DMTF contractors instead of waiting for volunteer work

**Comment by mraineri** [comment]
11/2: The group thinks there is still value in supporting Python2 for the foreseeable future; might want to clone this repo (or branch it), or possible figure out a way to make it run on both.

**Comment by pboyd04** [comment]
There are some things this tool does that simply cannot be done under Python 3 such as this bit: 
sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)
sys.stderr = os.fdopen(sys.stderr.fileno(), 'w', 0)

Can we do without this?

**Comment by mraineri** [comment]
PR merged
